language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: qEB/bw4Z508PS1UYsgqD+ktdYS12S90a881Ua6kkz2jTwiiNu8Uwzl4dGckrZLX8SL6wIadxfVUXZFH8SC1v090p/+ktZdi6ZGOPeanBhUIcYYcNxlKWfqwV4SI1b2MqflL9UuY9YypQ8k0p9mwRjQNkVtCDViAZ5CZ5oPKPL8oUOEXv8O2lejpIDwvaaJowLpCbxWZiarycXHHoqCC9dJqj2Ce1GolBlDzrTNV+ADhwAFgbuqJwcMvG6GSJGcKU/YC1h3jzuWPUr9pqmov9ZRD9JqHEC0QigDFnAEzI7JWupHSj1LeaLV66uceuW9FiedqTQcpAey6Pgo7GgRi7Z9qEILkmRknrsqfeQECOl0QnDQuRNCOWUajZ2JvB6BArRq6gZ1uqOa/jKRzB04cEA06UfQI4/l2ir83neZ6UPqJEmlLdI8pJBWwOYDy+iOgMds6MsL08nfCe5Q3YFFkJwwMX6m5AkS7ScytMdEzLSUGEXeov6PjSnrvd38bSbYU0Kce4Gg3gyAw5IvIw9cTtB+vX0lijcroroigBGvBKdGQzXO+DOqN3MfsVtAoDDvXhfxiRCX9Wb4NTA84SUXVf6P+nPYwCUif1ojm45L+MJ59IQLuM/tWBpIvUHNqrJEzLizHi9nU6sTBnx/Tyq6lNzCNM40Ngc/l5LUXJvDFMy34=
  app: cryptic-earth-41578
  on:
    repo: thinkful-ei21/harley-travisci-with-mongoose
    branch: feature/with-tests
